"""Processing is incremental across the board, and incremental never duplicates.

Owner decision: bronze and silver read incrementally with a watermark. Silver reads bronze by
`_lakelogic_processed_at` and upserts (merge on primary_key), so a re-read or updated bronze
record replaces its silver row instead of adding a second one. Gold follows where it can be
correct; aggregates stay full (see GOLD_FULL).

The effective materialization strategy is the contract's own `materialization.strategy`, else
the system default (`_system.yaml` materialization.<layer>, then `_all`) — the same
setdefault merge DomainRegistry performs.

WHAT THIS WOULD CATCH
    A new silver contract left on `load_mode: full`; a silver incremental contract without a
    watermark; an incremental silver/gold contract that appends or overwrites (duplicates or
    data loss on the next batch); a merge without a primary_key.

    python -m pytest databricks/tests
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[2] / "domains_rideflow"
WATERMARK = "_lakelogic_processed_at"

#: Bronze exceptions to incremental — none. (PDF extraction and city_master are incremental:
#: the engine filters landing files by mtime before extraction.)
BRONZE_FULL: dict[str, str] = {}

#: Gold contracts left on a full reload, each with the reason.
GOLD_FULL = {
    "gold_dim_date": "generated by external_logic (calendar range); no source to watermark",
    "gold_agg_acquisition_roi": "aggregate (GROUP BY date); a batch would overwrite with partial sums",
    "gold_fact_payment_reconciliation": "aggregate (GROUP BY created_date, currency)",
    "gold_dim_driver_360": "per-driver aggregates (lifetime payouts GROUP BY driver_id)",
    "gold_fact_revenue_daily": "aggregate (GROUP BY kpi_date, city_code, vehicle_type)",
    "gold_mart_acquisition_cost": "aggregate (GROUP BY kpi_date, channel, campaign_id)",
    "gold_mart_marketplace_health": "aggregate (GROUP BY kpi_date, city_code)",
    "gold_fact_trip_daily_kpis": "aggregate (GROUP BY kpi_date, city_code)",
    "gold_fact_rider_daily_metrics": "aggregate (GROUP BY rider_id, activity_date)",
    "gold_dim_driver_scorecard": "per-driver lifetime aggregates (GROUP BY driver_id)",
}


def _load(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _contracts(layer: str) -> list[Path]:
    return sorted(ROOT.glob(f"*/*/contracts/{layer}/*.yaml"))


def _name(path: Path) -> str:
    return path.stem.rsplit("_v", 1)[0]


def _effective_strategy(path: Path, layer: str) -> str | None:
    own = (_load(path).get("materialization") or {}).get("strategy")
    if own:
        return own
    system = _load(path.parents[2] / "_system.yaml").get("materialization") or {}
    return (system.get(layer) or {}).get("strategy") or (system.get("_all") or {}).get("strategy")


def _ids(paths):
    return [p.stem for p in paths]


BRONZE, SILVER, GOLD = _contracts("bronze"), _contracts("silver"), _contracts("gold")


def test_the_contract_inventory_is_found():
    assert len(BRONZE) >= 20 and len(SILVER) >= 20 and len(GOLD) >= 30


def test_the_exception_lists_name_real_contracts():
    names = {_name(p) for p in BRONZE + GOLD}
    assert set(BRONZE_FULL) | set(GOLD_FULL) <= names


@pytest.mark.parametrize("path", BRONZE, ids=_ids(BRONZE))
def test_bronze_is_incremental_with_a_watermark(path):
    if _name(path) in BRONZE_FULL:
        pytest.skip(BRONZE_FULL[_name(path)])
    src = _load(path)["source"]
    assert src.get("load_mode") == "incremental", f"{path.name} is not incremental"
    assert src.get("watermark_strategy") == "pipeline_log" or src.get("watermark_field"), (
        f"{path.name} is incremental without a watermark"
    )


@pytest.mark.parametrize("path", SILVER, ids=_ids(SILVER))
def test_silver_reads_bronze_incrementally_by_processed_at(path):
    src = _load(path)["source"]
    assert src.get("load_mode") == "incremental", f"{path.name} is not incremental"
    assert src.get("watermark_field") == WATERMARK, f"{path.name} watermark is not {WATERMARK}"


@pytest.mark.parametrize("path", SILVER, ids=_ids(SILVER))
def test_incremental_silver_upserts_on_its_primary_key(path):
    assert _effective_strategy(path, "silver") == "merge", (
        f"{path.name}: an incremental batch must merge, not append/overwrite"
    )
    assert _load(path).get("primary_key"), f"{path.name}: merge needs a primary_key"


@pytest.mark.parametrize("path", GOLD, ids=_ids(GOLD))
def test_gold_is_incremental_unless_listed(path):
    c = _load(path)
    mode = (c.get("source") or {}).get("load_mode")
    if _name(path) in GOLD_FULL:
        assert mode == "full", f"{path.name} is listed as full but is {mode}; update GOLD_FULL"
        return
    assert mode == "incremental", f"{path.name} is full but not listed in GOLD_FULL"
    fact_type = ((c.get("materialization") or {}).get("fact") or {}).get("type")
    if fact_type == "transaction":
        # Immutable events: the engine REQUIRES append for a transaction fact
        # ("Fact table type 'transaction' requires strategy 'append'").
        assert _effective_strategy(path, "gold") == "append", f"{path.name}: transaction facts append"
        return
    assert _effective_strategy(path, "gold") in ("merge", "scd2"), (
        f"{path.name}: incremental gold must merge/scd2 so re-emitted silver rows don't duplicate"
    )
    assert c.get("primary_key"), f"{path.name}: merge/scd2 needs a primary_key"
